name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m poetry install
          python -m poetry run python -m django startproject core
          mv app core
          echo "AUTH_USER_MODEL = 'users.User'" >> core/settings.py
          echo "INSTALLED_APPS += ['app', 'app.books', 'app.users', 'drf_redesign', 'rest_framework']" >> core/settings.py
          echo "from django.urls import include" >> core/urls.py
          echo "urlpatterns += [path('', include('app.urls'))" >> core/urls.py

      - name: Run the app
        run: |
          source .venv/bin/activate
          python -m poetry run python core/manage.py check
